### ISSUE TITLE
Pull Request "View diff on github" doesn't match

### ISSUE THREAD

**Issue by scpeters** [philipstarkey/bitbucket-hg-exporter#22]
I was just looking at one of your examples to see how the "View diff on github" looks, but in the example I looked at, the diff's don't seem to match.

I found this github commit that references pull request 50, submitted by `chrisjbillington`:

* https://github.com/labscript-suite/labscript/commit/21d0b1a5cdad1fdb7e3545dd7baa6e64bfd009b5

So I looked up pull request 50 in github-pages:

* https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/labscript/pull-requests/50/page/1

Then I clicked on "View diff on github", which points to the following link:

* https://github.com/labscript-suite/labscript/compare/7186e49166b9ae1ff6eb545ac53c5f4f74d07054..3a6da1be6613731da1f5e829dc507c24ac997935

And the comparison diff doesn't seem to match the commit diff. Maybe there's something weird about this commit history, but it's not making sense to me.

**Comment by philipstarkey** [comment]
Yeah I don't understand that either. Fortunately it looks like the diff on the GitHub pages site matches the diff on the original BitBucket repo: https://bitbucket.org/labscript_suite/labscript/pull-requests/50/set-the-target-cycle-time/diff

I have no idea why the merge commit diff on GitHub is wrong...

The commit with the correct diff is on a separate branch (cycle time), which is what GitHub pages points to.

I don't have any control over the GitHub generated diffs, these are all done by the GitHub source import tool.

**Comment by philipstarkey** [comment]
Had chance to look into it a bit more...

The diff you are seeing is the diff of PR49. It's confused about which was the master branch and which direction the feature branch was being merged. A graphical representation shows what I would consider to be master  being merged into the feature branch for PR49 and then that feature branch being merged into the feature branch for PR50...or something like that.

Interestingly, BitBucket has almost done the same thing, except it shows what I would consider master being merged into both feature branches for PR49 and PR50, which seems totally backwards. That may be because of the way @chrisjbillington was closing branches and merging or it might be BitBuckets fault. 

Either way, I'm less likely to blame my tool or GitHub at this point so I'm going to close this for now unless any other information comes to light.

**Comment by chrisjbillington** [comment]
I see bitbucket's diffs looking correct -  where are you seeing what looks like default being merged into master Phil?

To me this diff looks like the feature branch being merged into default as expected: https://bitbucket.org/labscript_suite/labscript/commits/5308a0ecbe94f38e67a6d6ffac5a00c83a73ead1

**Comment by philipstarkey** [comment]
The diffs are correct, but the graph here is not: https://bitbucket.org/labscript_suite/labscript/commits/

But I see now that the graph on BitBucket differs from the graph in TortoiseHg, which implies that BitBucket is probably using some transformation between hg -> git -> drawing the graph (since BitBucket now primarily supports git).

I guess I could add an option to use hg-fast-export locally rather than the GitHub source import tool...I've opened #23 for continued discussion.

**Comment by chrisjbillington** [comment]
I think it's just about the drawing of the graph - bitbucket just displays the 'main' branch on the right instead of the left like tortoisehg does. The rightmost part of its graph is a straight line and the feature branches stick out on the left, so it's still well represented which is branching off and being merged into what, just a different convention for displaying it.

**Comment by philipstarkey** [comment]
For most of the merges, yes...but the merge of PR49 looks to me like master is going into the branch.

**Comment by chrisjbillington** [comment]
Ah, you're right. It does seem limited to the graph drawing though, and doesn't seem to correspond to any data in the repo being incorrect (the commits are all still in the right branches). I would guess it's jsut the graph drawing algorithm (whether it is fed through some git machinery or not).
