### ISSUE TITLE
Provide option to use hg-fast-import to convert to git instead of GitHub source import tool

### ISSUE THREAD

**Issue by philipstarkey** [philipstarkey/bitbucket-hg-exporter#23]
Given the odd detection of the master branch (highlighted in #22) which results in erroneous commit diffs in the commit log, it might be worth considering adding an option to use hg-fast-export instead of the GitHub source importer. (@chrisjbillington suspects that GitHub have a bug similar to frej/fast-export#19)

However, doing this is a bit complex because hg-fast-export requires Python 2.7, but my tool requires Python 3.7+.

Perhaps the appropriate solution is to just pause my tool and ask users to resume once they have a local git repo, at which point my tool can resume and push to GitHub.

**Comment by chrisjbillington** [comment]
> Perhaps the appropriate solution is to just pause my tool and ask users to resume once they have a local git repo, at which point my tool can resume and push to GitHub.

This seems like it could be good! Since it's a one-off tool, there's not much point automating that part too much, plus those with a mostly linear history won't care about this issue.

I can see that hg-fast-export has some attempts to port it to Python 3, but these are so far entirely uninformed about how mercurial itself has handled the Python 3 transition, so those porting efforts are inadequate - they're expecting python 3 unicode strings when mercurial under Python 3 is going to continue to return bytestrings for everything (a poor decision IMHO that will continue to trip up all code that has to interact with the mercurial Python API well into the future).

hg-fast-export accepts an author mapping file - so the conversion can do the author remapping at that point - presumably github won't let you do automatically remap after pushing if it doesn't have any way of knowing it was an imported repo.

**Comment by chrisjbillington** [comment]
I've made the following tool:

https://github.com/chrisjbillington/hg-export-tool

For converting a number of hg repositories to git repositories locally using `hg-fast-export`. Before conversion it amends the commits of anonymous/bookmarked heads to give them unique branch names so that they survive the transition, and it gives the correct ordering of parents on merge commits courtesy of `hg-fast-export` having fixed the 2014 bug.

It takes as input a filepath to a file containing JSON mapping mercurial repository paths to the desired git repository paths (which must not already exist). Any other arguments are passed to `hg-fast-export`

It has a script that will generate a list of authors present in all the mercurial repositories, in the appropriate format for passing to `hg-fast-export` (and therefore my conversion tool) with the `-A` command line option. The file it generates can be edited to actually specify the mapping, otherwise it is just a default conversion (all email addresses devnull@localhost if not present already).

Perhaps the way forward is for your tool to ask the user if they want to use github's importer or not, saying its faster and fine for mostly linear history, otherwise they can use my tool or something else if they like.

If they choose to not use github's importer, your tool could create the JSON file saying that it has a bunch of local mercurial repositories, and where it would like the git repositories to be created. It then pauses, or stores its state to later be resumed, or whatever, and picks up once the git repos exist.

It's a pain that they are two separate tools, but as mentioned since this one is PY3 whereas `hg-fast-export` is necessarily PY2, the user is going to need two Python environments anyway to use both, so it would be super tricky to merge them.

My tool was a little bit of a pain to get working on Windows, you need to have git bash and provide the path to git bash for it to work. There were a few other rough edges on Windows, but it's working at least for my example case now. I had to bundle a patched `hg-fast-export` to get it to work on Windows, otherwise it crashed because some unix tools were not available (though they aren't necessary, so my patch is just to remove the unneeded usage of them).

**Comment by philipstarkey** [comment]
This feature has been available since v0.6.0, closing.
